// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Platform7$Platform7 from "platform7/src/Platform7.bs.js";

var b = Platform7$Platform7.a;

var a = "I'm platform 8";

export {
  b ,
  a ,
  
}
/* No side effect */
